### PR TITLE
doc: add section discouraging git pull

### PR DESCRIPTION
**Pull request by danielolsen**
### Purpose
Add a section discouraging `git pull` with no additional arguments, plus some other small tweaks.

### What the code is doing
No code.

### Testing
Built the docs manually, they look alright.

### Time estimate
15 minutes.

### CODE REVIEW

**Review by jon-hagg — APPROVED** [review]

**Review by BainanXia — APPROVED** [review]
Nice. Thanks!

**Comment by merrielle** [comment]
`git config --global pull.rebase true` makes `git pull` default to rebase. I recommend adding a note about that in the docs.

**Comment by danielolsen** [comment]
> `git config --global pull.rebase true` makes `git pull` default to rebase. I recommend adding a note about that in the docs.
> 
> At first I was confused about why git pull was bad and then I remembered that config option isn't the default. 😅

I added a bit about `git config`, let me know what you think.

**Review by merrielle — APPROVED** [review]
Updated docs look great!

**Pull request merged**
